stages:
  - publish

variables:
  REGISTRY: docker.io
  REGISTRY_IMAGE: $DOCKER_HUB_USER/revealjs

image: docker:latest

services:
  - docker:dind

publish:docker:
  stage: publish
  script: |
    docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD" $REGISTRY
    docker build --pull -t "$REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" .
    docker push "$REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
    docker tag "$REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" "$REGISTRY_IMAGE:latest"
    docker push "$REGISTRY_IMAGE:latest"
  only:
    - /^v*/
  except:
    - branches
